server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tvmall
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: springcloud-provider
mybatis:
  type-aliases-package: cn.yunhe.java.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka
